### ISSUE TITLE
is conversion to fasta from wrong fastq offset?

### ISSUE THREAD

**Issue by niko-balanis** [aditya-88/ASAP#3]
Not 100% sure but in your code when you convert the abi to fastq you use

Forward_fastq = SeqIO.convert(Forward_seq, "abi", forward_file.name, "fastq")

according to biopython documentation the fastq format is ascii +33
![image](https://user-images.githubusercontent.com/11866972/134183959-ae6d940f-743f-453d-8fe6-892a9fc27bb6.png)
https://biopython.org/wiki/SeqIO

But you use this as if it comes from a 64 ascii offset fastq

`os.system(
            seqtk
            + " seq -aQ64 -q10 -n N "
            + forward_file.name[:-6]
            + "_QC.fastq"
            + " >"
            + forward_file.name[:-23]
            + "_consensus.fasta"
        )`

should it not be (as the default is 33 offset, maybe you have to also adjust the -q10 too?)

`os.system(
            seqtk
            + " seq -a -q10 -n N "
            + forward_file.name[:-6]
            + "_QC.fastq"
            + " >"
            + forward_file.name[:-23]
            + "_consensus.fasta"
        )`

**Comment by addityea** [comment]
Hi @niko-balanis !

First of all, my apologies for such a delayed response. It has been some years since ASAP was published and I got caught up in a lot of other work. But, I'm elated to note that people still have an interest in this piece of software! Thank you, all of you!

In regard to that, I have revamped the code and have changed the way QC is handled, thanks to your comment. I was using Q10 to match base 64 coding but now I have changed to 33 and moved the Q cut-off to 23, which corresponds to ~0.005 p-value.

Thank you and hope this software helps you out!

**Fixed [c57437b](https://github.com/aditya-88/ASAP/commit/c57437be1a369b1679dc261f9dba98ab45c0c53d)**
